<?php

namespace Socodo\Framework\Commands;

class GenerateControllerCommand extends GenerateCommand
{
    /** @var string Command name. */
    protected string $name = 'controller';

    /** @var string Command description. */
    protected string $description = 'Generate a new controller.';

    /**
     * Generate a PHP class string.
     *
     * @param string $className
     * @return string
     */
    protected function getGeneratedClassString (string $className): string
    {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace App\\Controllers;';
        $lines[] = '';
        $lines[] = 'use Socodo\\Framework\\Controller\\Controller;';
        $lines[] = 'use Psr\\Http\\Message\\ServerRequestInterface;';
        $lines[] = 'use Socodo\\Router\\Attributes\\Prefix;';
        $lines[] = 'use Socodo\\Router\\Attributes\\Get;';
        $lines[] = '';
        $lines[] = '#[Prefix(\'/' . strtolower($className) . '\')]';
        $lines[] = 'class ' . $className . ' extends Controller';
        $lines[] = '{';
        $lines[] = '    /**';
        $lines[] = '     * Constructor.';
        $lines[] = '     *';
        $lines[] = '     * @param ServerRequestInterface $request';
        $lines[] = '     */';
        $lines[] = '    public function __construct (ServerRequestInterface $request)';
        $lines[] = '    {';
        $lines[] = '        parent::__construct($request);';
        $lines[] = '        // TODO: Change the autogenerated stub';
        $lines[] = '    }';
        $lines[] = '';
        $lines[] = '    /**';
        $lines[] = '     * Autogenerated index() method.';
        $lines[] = '     *';
        $lines[] = '     * @return string';
        $lines[] = '     */';
        $lines[] = '    #[Get(\'/index\')]';
        $lines[] = '    public function index (): string';
        $lines[] = '    {';
        $lines[] = '        return \'Hello, World!\';';
        $lines[] = '    }';
        $lines[] = '}';

        return implode("\n", $lines);
    }
}